In [1]:
# 1>i.Create a 1D array of the first 10 positive integers.
#Print the array.
#Find the sum of all elements in the array.
#Calculate the mean of the elements.

import numpy as np
array=[1,2,3,4,5,6,7,8,9,10]
print(array)
array_sum=np.sum(array)
print(array_sum)
array_mean=np.mean(array)
array_mean

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55


5.5

In [2]:
#1>ii.Create a 2D array of shape (3, 4) with random integers between 1 and 10.
#Print the array.
#Find the maximum and minimum values in the array.
#Calculate the sum of each row and each column.
import numpy as np
array=np.random.randint(1,11,size=(3,4))
print(array)
max_value=np.max(array)
min_value=np.min(array)
print(max_value,min_value)
row_sums = np.sum(array, axis=1)
column_sums = np.sum(array, axis=0)
print(row_sums,column_sums)

[[ 1 10 10  7]
 [ 5  2  5  4]
 [ 4  2  2  1]]
10 1
[28 16  9] [10 14 17 12]


In [3]:
#2.i>Create a 1D array of 20 random integers between 1 and 100.
#Print the array.
#Print the elements from index 5 to 15.
#Print every second element of the array.
import numpy as np
arr=np.random.randint(1,101,size=20)
print(arr)
print("index 5 to 15",arr[5:16])
print("second element",arr[::2])

[28  3 23 12 74 22 84 30 25 62 63 88 15 39 24 94 34 54 14 53]
index 5 to 15 [22 84 30 25 62 63 88 15 39 24 94]
second element [28 23 74 84 25 63 15 24 34 14]


In [4]:
#2.ii>Create a 2D array of shape (5, 5) with random integers between 1 and 50.
#Print the array.
#Extract and print the second row.
#Extract and print the third column.
#Extract and print a 3x3 subarray from the original array.
import numpy as np
arr=np.random.randint(1,11,size=(5,5))
print(arr)
second_row=arr[1]
print("\nSecond row:\n",second_row)
third_column=arr[:,2]
print("\nthird row:\n",third_column)
subarray_3x3 = arr[1:4, 1:4]
print("\n3x3 Subarray:\n", subarray_3x3)

[[ 1  7  4  8  2]
 [ 9  7  8  4 10]
 [ 7  4  8  7  8]
 [ 9 10  3  1  4]
 [ 3  9 10 10 10]]

Second row:
 [ 9  7  8  4 10]

third row:
 [ 4  8  8  3 10]

3x3 Subarray:
 [[ 7  8  4]
 [ 4  8  7]
 [10  3  1]]


In [5]:
#3.i>Create two 1D arrays of 10 random integers each.
#Concatenate the two arrays.
#Sort the concatenated array.
#Find the unique elements in the concatenated array.
import numpy as np
arr1=np.random.randint(1,100,size=10)
arr2=np.random.randint(1,100,size=10)
print(arr1,arr2)
concatenate_arr=np.concatenate((arr1,arr2))
print("concatenate array\n",concatenate_arr)
sorted_arr=np.sort(concatenate_arr)
print("sorted array\n",sorted_arr)
unique_ele=np.unique(sorted_arr)
print("unique ele\n",unique_ele)

[82 61 77 31 78 46 43 22 73 34] [74 34 18 82 87 47  9 54 54 50]
concatenate array
 [82 61 77 31 78 46 43 22 73 34 74 34 18 82 87 47  9 54 54 50]
sorted array
 [ 9 18 22 31 34 34 43 46 47 50 54 54 61 73 74 77 78 82 82 87]
unique ele
 [ 9 18 22 31 34 43 46 47 50 54 61 73 74 77 78 82 87]


In [6]:
#3.ii>Create a 2D array of shape (4, 4) with random integers between 1 and 20.
#Print the array.
#Flatten the array into a 1D array.
#Reshape the flattened array back into a 2D array of shape (2, 8).
import numpy as np
arr=np.random.randint(1,21,size=(4,4))
print(arr)
flattened_arr = arr.flatten()
print("flattened arr\n",flattened_arr)
reshape_arr=flattened_arr.reshape(2,8)
print("reshape arr\n",reshape_arr)

[[14  2  7 10]
 [11  1 14 14]
 [ 2 15 10  7]
 [ 8 13 13 20]]
flattened arr
 [14  2  7 10 11  1 14 14  2 15 10  7  8 13 13 20]
reshape arr
 [[14  2  7 10 11  1 14 14]
 [ 2 15 10  7  8 13 13 20]]


In [7]:
#4.i>Create a 1D array of 15 random integers between 1 and 50.
#Print the array.
#Calculate and print the standard deviation of the array.
#Find and print the index of the maximum value in the array.
#Normalize the array (scale the values to a range between 0 and 1).
import numpy as np
arr=np.random.randint(1,51,size=15)
print(arr)
std_dev= np.std(array)
print("Standard Deviation:", std_dev)
max_index=np.max(arr)
print("max\n",max_index)
normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("Normalized Arr:", normalized_arr)

[14 15 23 31 23 43 43 28 12 40 31 30 44 34 49]
Standard Deviation: 3.0402393911591163
max
 49
Normalized Arr: [0.05405405 0.08108108 0.2972973  0.51351351 0.2972973  0.83783784
 0.83783784 0.43243243 0.         0.75675676 0.51351351 0.48648649
 0.86486486 0.59459459 1.        ]


In [8]:
#4.ii>Create two 2D arrays of shape (3, 3) with random integers between 1 and 10.
#Print both arrays.
#Perform element-wise addition, subtraction, and multiplication of the arrays.
#Calculate the dot product of the arrays.
import numpy as np
arr1=np.random.randint(1,11,size=(3,3))
arr2=np.random.randint(1,11,size=(3,3))
print(arr1)
print(arr2)
element_wise_addition = arr1 + arr2
element_wise_subtraction = arr1 - arr2
element_wise_multiplication = arr1 * arr2
dot_product = np.dot(arr1, arr2)
element_wise_addition, element_wise_subtraction, element_wise_multiplication, dot_product

[[7 1 4]
 [9 1 9]
 [9 3 1]]
[[ 6  1 10]
 [ 9  3  6]
 [10  9  1]]


(array([[13,  2, 14],
        [18,  4, 15],
        [19, 12,  2]]),
 array([[ 1,  0, -6],
        [ 0, -2,  3],
        [-1, -6,  0]]),
 array([[42,  1, 40],
        [81,  3, 54],
        [90, 27,  1]]),
 array([[ 91,  46,  80],
        [153,  93, 105],
        [ 91,  27, 109]]))